import { RoleplayMessageContext } from "../types";

const ACTOR_LABELS: Record<RoleplayMessageContext["actorAction"], string> = {
  triggered: "Generated by",
  continued: "Continued by",
};

export const buildRoleplayMessageHeader = (
  context: RoleplayMessageContext,
): string => {
  const sourceLine = `<@${context.sourceAuthorId}> [original message](${context.sourceMessageUrl})`;
  const actorLine = `${ACTOR_LABELS[context.actorAction]} <@${context.actorUserId}>`;

  return `${sourceLine}\n${actorLine}`;
};
