import { RoleplayMessageContext } from "../types";

const ACTOR_LABELS: Record<RoleplayMessageContext["actorAction"], string> = {
  triggered: "Generated by",
  continued: "Continued by",
};

export const buildRoleplayActorLine = (
  context: RoleplayMessageContext,
): string => `${ACTOR_LABELS[context.actorAction]} <@${context.actorUserId}>`;
