export const REACTION_REWARD_AMOUNT = 5;

export const TEN_PLUS_REACTION_THRESHOLD = 10;
export const TEN_PLUS_REACTION_BONUS = 50;

export const TWENTY_FIVE_PLUS_REACTION_THRESHOLD = 25;
export const TWENTY_FIVE_PLUS_REACTION_BONUS = 100;
